//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Titular()
        {
            this.Dependiente = new HashSet<Dependiente>();
        }
    
        public int sec_titular { get; set; }
        public string cedula_titular { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public int sec_plan { get; set; }
        public decimal valor_total { get; set; }
        public int sec_tipoCuenta { get; set; }
        public string noCuenta { get; set; }
        public int sec_banco { get; set; }
        public int sec_empresa { get; set; }
        public int sec_tipoDoc { get; set; }
        public System.DateTime fecha_Nacimiento { get; set; }
        public int genero { get; set; }
        public System.DateTime fecha_Creacion { get; set; }
        public short estado { get; set; }
        public string div_pago { get; set; }
    
        public virtual Banco Banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dependiente> Dependiente { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual TipoCuenta TipoCuenta { get; set; }
    }
}
