//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BusinessService.CoberturaServ1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processPackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindIdentificationNumberOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::BusinessService.Properties.Settings.Default.BusinessService_CoberturaServ1_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event processPackageCompletedEventHandler processPackageCompleted;
        
        /// <remarks/>
        public event FindIdentificationNumberCompletedEventHandler FindIdentificationNumberCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/processPackage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string processPackage(string processId) {
            object[] results = this.Invoke("processPackage", new object[] {
                        processId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void processPackageAsync(string processId) {
            this.processPackageAsync(processId, null);
        }
        
        /// <remarks/>
        public void processPackageAsync(string processId, object userState) {
            if ((this.processPackageOperationCompleted == null)) {
                this.processPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessPackageOperationCompleted);
            }
            this.InvokeAsync("processPackage", new object[] {
                        processId}, this.processPackageOperationCompleted, userState);
        }
        
        private void OnprocessPackageOperationCompleted(object arg) {
            if ((this.processPackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processPackageCompleted(this, new processPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindIdentificationNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public personaSd FindIdentificationNumber(string identificationNumber) {
            object[] results = this.Invoke("FindIdentificationNumber", new object[] {
                        identificationNumber});
            return ((personaSd)(results[0]));
        }
        
        /// <remarks/>
        public void FindIdentificationNumberAsync(string identificationNumber) {
            this.FindIdentificationNumberAsync(identificationNumber, null);
        }
        
        /// <remarks/>
        public void FindIdentificationNumberAsync(string identificationNumber, object userState) {
            if ((this.FindIdentificationNumberOperationCompleted == null)) {
                this.FindIdentificationNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindIdentificationNumberOperationCompleted);
            }
            this.InvokeAsync("FindIdentificationNumber", new object[] {
                        identificationNumber}, this.FindIdentificationNumberOperationCompleted, userState);
        }
        
        private void OnFindIdentificationNumberOperationCompleted(object arg) {
            if ((this.FindIdentificationNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindIdentificationNumberCompleted(this, new FindIdentificationNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class personaSd {
        
        private int secPersonaField;
        
        private bool secPersonaFieldSpecified;
        
        private tipoIdentificacionSd codTipoIdentificacionField;
        
        private string identificacionField;
        
        private string denominacionField;
        
        private personaNaturalSd personaNaturalField;
        
        private relacionSd[] relacionField;
        
        private relacionSd[] relacionBaseField;
        
        private relacionSd conyugeField;
        
        private direccionSd[] direccionField;
        
        private telefonoSd[] telefonoSinDireccionField;
        
        private vehiculoSd[] vehiculoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int secPersona {
            get {
                return this.secPersonaField;
            }
            set {
                this.secPersonaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secPersonaSpecified {
            get {
                return this.secPersonaFieldSpecified;
            }
            set {
                this.secPersonaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoIdentificacionSd codTipoIdentificacion {
            get {
                return this.codTipoIdentificacionField;
            }
            set {
                this.codTipoIdentificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string denominacion {
            get {
                return this.denominacionField;
            }
            set {
                this.denominacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public personaNaturalSd personaNatural {
            get {
                return this.personaNaturalField;
            }
            set {
                this.personaNaturalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("relacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public relacionSd[] relacion {
            get {
                return this.relacionField;
            }
            set {
                this.relacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("relacionBase", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public relacionSd[] relacionBase {
            get {
                return this.relacionBaseField;
            }
            set {
                this.relacionBaseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public relacionSd conyuge {
            get {
                return this.conyugeField;
            }
            set {
                this.conyugeField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("direccion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public direccionSd[] direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("telefonoSinDireccion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public telefonoSd[] telefonoSinDireccion {
            get {
                return this.telefonoSinDireccionField;
            }
            set {
                this.telefonoSinDireccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("vehiculo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vehiculoSd[] vehiculo {
            get {
                return this.vehiculoField;
            }
            set {
                this.vehiculoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class tipoIdentificacionSd {
        
        private string tipoIdentificacionField;
        
        private string codTipoIdentificacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codTipoIdentificacion {
            get {
                return this.codTipoIdentificacionField;
            }
            set {
                this.codTipoIdentificacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class canalSd {
        
        private string canalField;
        
        private short secCanalField;
        
        private bool secCanalFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short secCanal {
            get {
                return this.secCanalField;
            }
            set {
                this.secCanalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secCanalSpecified {
            get {
                return this.secCanalFieldSpecified;
            }
            set {
                this.secCanalFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class vehiculoSd {
        
        private int secVehiculoField;
        
        private bool secVehiculoFieldSpecified;
        
        private string placaField;
        
        private string chasisField;
        
        private string marcaField;
        
        private decimal avaluoField;
        
        private bool avaluoFieldSpecified;
        
        private string modeloField;
        
        private int anioField;
        
        private string usrCreacionField;
        
        private System.DateTime tsCreacionField;
        
        private bool tsCreacionFieldSpecified;
        
        private string usrModificacionField;
        
        private System.DateTime tsModificacionField;
        
        private bool tsModificacionFieldSpecified;
        
        private canalSd secCanalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int secVehiculo {
            get {
                return this.secVehiculoField;
            }
            set {
                this.secVehiculoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secVehiculoSpecified {
            get {
                return this.secVehiculoFieldSpecified;
            }
            set {
                this.secVehiculoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string chasis {
            get {
                return this.chasisField;
            }
            set {
                this.chasisField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal avaluo {
            get {
                return this.avaluoField;
            }
            set {
                this.avaluoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avaluoSpecified {
            get {
                return this.avaluoFieldSpecified;
            }
            set {
                this.avaluoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int anio {
            get {
                return this.anioField;
            }
            set {
                this.anioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usrCreacion {
            get {
                return this.usrCreacionField;
            }
            set {
                this.usrCreacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime tsCreacion {
            get {
                return this.tsCreacionField;
            }
            set {
                this.tsCreacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tsCreacionSpecified {
            get {
                return this.tsCreacionFieldSpecified;
            }
            set {
                this.tsCreacionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usrModificacion {
            get {
                return this.usrModificacionField;
            }
            set {
                this.usrModificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime tsModificacion {
            get {
                return this.tsModificacionField;
            }
            set {
                this.tsModificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tsModificacionSpecified {
            get {
                return this.tsModificacionFieldSpecified;
            }
            set {
                this.tsModificacionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public canalSd secCanal {
            get {
                return this.secCanalField;
            }
            set {
                this.secCanalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class tipoTelefonoSd {
        
        private short codTipoTelefonoField;
        
        private bool codTipoTelefonoFieldSpecified;
        
        private string tipoTelefonoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short codTipoTelefono {
            get {
                return this.codTipoTelefonoField;
            }
            set {
                this.codTipoTelefonoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codTipoTelefonoSpecified {
            get {
                return this.codTipoTelefonoFieldSpecified;
            }
            set {
                this.codTipoTelefonoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoTelefono {
            get {
                return this.tipoTelefonoField;
            }
            set {
                this.tipoTelefonoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class telefonoSd {
        
        private int secTelefonoField;
        
        private bool secTelefonoFieldSpecified;
        
        private string codAreaField;
        
        private string nroTelefonoField;
        
        private tipoTelefonoSd codTipoTelefonoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int secTelefono {
            get {
                return this.secTelefonoField;
            }
            set {
                this.secTelefonoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secTelefonoSpecified {
            get {
                return this.secTelefonoFieldSpecified;
            }
            set {
                this.secTelefonoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codArea {
            get {
                return this.codAreaField;
            }
            set {
                this.codAreaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nroTelefono {
            get {
                return this.nroTelefonoField;
            }
            set {
                this.nroTelefonoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoTelefonoSd codTipoTelefono {
            get {
                return this.codTipoTelefonoField;
            }
            set {
                this.codTipoTelefonoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class tipoDireccionSd {
        
        private short codTipoDireccionField;
        
        private bool codTipoDireccionFieldSpecified;
        
        private string tipoDireccionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short codTipoDireccion {
            get {
                return this.codTipoDireccionField;
            }
            set {
                this.codTipoDireccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codTipoDireccionSpecified {
            get {
                return this.codTipoDireccionFieldSpecified;
            }
            set {
                this.codTipoDireccionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDireccion {
            get {
                return this.tipoDireccionField;
            }
            set {
                this.tipoDireccionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class direccionSd {
        
        private int secDireccionField;
        
        private bool secDireccionFieldSpecified;
        
        private string direccionField;
        
        private tipoDireccionSd tipoDireccionField;
        
        private provinciaSd provinciaField;
        
        private parroquiaSd parroquiaField;
        
        private cantonSd cantonField;
        
        private string referenciaField;
        
        private string principalTrField;
        
        private string numeroTrField;
        
        private string secundariaTrField;
        
        private string[] telefonoDireccionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int secDireccion {
            get {
                return this.secDireccionField;
            }
            set {
                this.secDireccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secDireccionSpecified {
            get {
                return this.secDireccionFieldSpecified;
            }
            set {
                this.secDireccionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoDireccionSd tipoDireccion {
            get {
                return this.tipoDireccionField;
            }
            set {
                this.tipoDireccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public provinciaSd provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public parroquiaSd parroquia {
            get {
                return this.parroquiaField;
            }
            set {
                this.parroquiaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cantonSd canton {
            get {
                return this.cantonField;
            }
            set {
                this.cantonField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string principalTr {
            get {
                return this.principalTrField;
            }
            set {
                this.principalTrField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroTr {
            get {
                return this.numeroTrField;
            }
            set {
                this.numeroTrField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string secundariaTr {
            get {
                return this.secundariaTrField;
            }
            set {
                this.secundariaTrField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("telefonoDireccion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] telefonoDireccion {
            get {
                return this.telefonoDireccionField;
            }
            set {
                this.telefonoDireccionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class provinciaSd {
        
        private short secProvinciaField;
        
        private bool secProvinciaFieldSpecified;
        
        private string provinciaField;
        
        private string codAreaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short secProvincia {
            get {
                return this.secProvinciaField;
            }
            set {
                this.secProvinciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secProvinciaSpecified {
            get {
                return this.secProvinciaFieldSpecified;
            }
            set {
                this.secProvinciaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codArea {
            get {
                return this.codAreaField;
            }
            set {
                this.codAreaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class parroquiaSd {
        
        private short secParroquiaField;
        
        private bool secParroquiaFieldSpecified;
        
        private string parroquiaField;
        
        private ushort cabeceraField;
        
        private bool cabeceraFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short secParroquia {
            get {
                return this.secParroquiaField;
            }
            set {
                this.secParroquiaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secParroquiaSpecified {
            get {
                return this.secParroquiaFieldSpecified;
            }
            set {
                this.secParroquiaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string parroquia {
            get {
                return this.parroquiaField;
            }
            set {
                this.parroquiaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort cabecera {
            get {
                return this.cabeceraField;
            }
            set {
                this.cabeceraField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cabeceraSpecified {
            get {
                return this.cabeceraFieldSpecified;
            }
            set {
                this.cabeceraFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class cantonSd {
        
        private short secCantonField;
        
        private bool secCantonFieldSpecified;
        
        private string cantonField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short secCanton {
            get {
                return this.secCantonField;
            }
            set {
                this.secCantonField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secCantonSpecified {
            get {
                return this.secCantonFieldSpecified;
            }
            set {
                this.secCantonFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string canton {
            get {
                return this.cantonField;
            }
            set {
                this.cantonField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class personaRelacionDto {
        
        private string identificacionField;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class relacionSd {
        
        private int secRelacionField;
        
        private bool secRelacionFieldSpecified;
        
        private personaRelacionDto personaRelacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int secRelacion {
            get {
                return this.secRelacionField;
            }
            set {
                this.secRelacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secRelacionSpecified {
            get {
                return this.secRelacionFieldSpecified;
            }
            set {
                this.secRelacionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public personaRelacionDto personaRelacion {
            get {
                return this.personaRelacionField;
            }
            set {
                this.personaRelacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class estadoCivilSd {
        
        private short codEstadoCivilField;
        
        private bool codEstadoCivilFieldSpecified;
        
        private string estadoCivilField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short codEstadoCivil {
            get {
                return this.codEstadoCivilField;
            }
            set {
                this.codEstadoCivilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codEstadoCivilSpecified {
            get {
                return this.codEstadoCivilFieldSpecified;
            }
            set {
                this.codEstadoCivilFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class paisSd {
        
        private short codPaisField;
        
        private bool codPaisFieldSpecified;
        
        private string paisField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short codPais {
            get {
                return this.codPaisField;
            }
            set {
                this.codPaisField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codPaisSpecified {
            get {
                return this.codPaisFieldSpecified;
            }
            set {
                this.codPaisFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class profesionSd {
        
        private string codProfesionRcField;
        
        private string profesionRcField;
        
        private short secProfesionField;
        
        private bool secProfesionFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codProfesionRc {
            get {
                return this.codProfesionRcField;
            }
            set {
                this.codProfesionRcField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string profesionRc {
            get {
                return this.profesionRcField;
            }
            set {
                this.profesionRcField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short secProfesion {
            get {
                return this.secProfesionField;
            }
            set {
                this.secProfesionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secProfesionSpecified {
            get {
                return this.secProfesionFieldSpecified;
            }
            set {
                this.secProfesionFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class personaJuridicaSd {
        
        private string identificacionField;
        
        private string razonSocialField;
        
        private string actividadIessField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string actividadIess {
            get {
                return this.actividadIessField;
            }
            set {
                this.actividadIessField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class empleoDependienteSd {
        
        private int secEmpleoDependienteField;
        
        private bool secEmpleoDependienteFieldSpecified;
        
        private string cargoField;
        
        private decimal mntSalarioField;
        
        private bool mntSalarioFieldSpecified;
        
        private System.DateTime fechaIngresoField;
        
        private bool fechaIngresoFieldSpecified;
        
        private System.DateTime fechaSalidaField;
        
        private bool fechaSalidaFieldSpecified;
        
        private personaJuridicaSd empleadorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int secEmpleoDependiente {
            get {
                return this.secEmpleoDependienteField;
            }
            set {
                this.secEmpleoDependienteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secEmpleoDependienteSpecified {
            get {
                return this.secEmpleoDependienteFieldSpecified;
            }
            set {
                this.secEmpleoDependienteFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal mntSalario {
            get {
                return this.mntSalarioField;
            }
            set {
                this.mntSalarioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mntSalarioSpecified {
            get {
                return this.mntSalarioFieldSpecified;
            }
            set {
                this.mntSalarioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaIngresoSpecified {
            get {
                return this.fechaIngresoFieldSpecified;
            }
            set {
                this.fechaIngresoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaSalida {
            get {
                return this.fechaSalidaField;
            }
            set {
                this.fechaSalidaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSalidaSpecified {
            get {
                return this.fechaSalidaFieldSpecified;
            }
            set {
                this.fechaSalidaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public personaJuridicaSd empleador {
            get {
                return this.empleadorField;
            }
            set {
                this.empleadorField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class actividadEconomicaSd {
        
        private short codActividadEconomicaField;
        
        private bool codActividadEconomicaFieldSpecified;
        
        private string actividadEconomicaSriField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short codActividadEconomica {
            get {
                return this.codActividadEconomicaField;
            }
            set {
                this.codActividadEconomicaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codActividadEconomicaSpecified {
            get {
                return this.codActividadEconomicaFieldSpecified;
            }
            set {
                this.codActividadEconomicaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string actividadEconomicaSri {
            get {
                return this.actividadEconomicaSriField;
            }
            set {
                this.actividadEconomicaSriField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class informacionAdicionalSd {
        
        private int secInformacionAdicField;
        
        private bool secInformacionAdicFieldSpecified;
        
        private string identificacionField;
        
        private string razonSocialField;
        
        private string nombreComercialField;
        
        private System.DateTime fechaInscripcionField;
        
        private bool fechaInscripcionFieldSpecified;
        
        private System.DateTime fechaInicioActividadesField;
        
        private bool fechaInicioActividadesFieldSpecified;
        
        private System.DateTime fechaCancelacionField;
        
        private bool fechaCancelacionFieldSpecified;
        
        private System.DateTime fechaSuspensionField;
        
        private bool fechaSuspensionFieldSpecified;
        
        private System.DateTime fechaReinicioField;
        
        private bool fechaReinicioFieldSpecified;
        
        private string principalField;
        
        private string numeroField;
        
        private string secundariaField;
        
        private string referenciaField;
        
        private string telefonoField;
        
        private string eMailField;
        
        private tipoIdentificacionSd tipoIdentificacionField;
        
        private provinciaSd provinciaField;
        
        private parroquiaSd parroquiaField;
        
        private cantonSd cantonField;
        
        private actividadEconomicaSd actividadEconomicaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int secInformacionAdic {
            get {
                return this.secInformacionAdicField;
            }
            set {
                this.secInformacionAdicField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secInformacionAdicSpecified {
            get {
                return this.secInformacionAdicFieldSpecified;
            }
            set {
                this.secInformacionAdicFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreComercial {
            get {
                return this.nombreComercialField;
            }
            set {
                this.nombreComercialField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaInscripcion {
            get {
                return this.fechaInscripcionField;
            }
            set {
                this.fechaInscripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInscripcionSpecified {
            get {
                return this.fechaInscripcionFieldSpecified;
            }
            set {
                this.fechaInscripcionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaInicioActividades {
            get {
                return this.fechaInicioActividadesField;
            }
            set {
                this.fechaInicioActividadesField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioActividadesSpecified {
            get {
                return this.fechaInicioActividadesFieldSpecified;
            }
            set {
                this.fechaInicioActividadesFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaCancelacion {
            get {
                return this.fechaCancelacionField;
            }
            set {
                this.fechaCancelacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCancelacionSpecified {
            get {
                return this.fechaCancelacionFieldSpecified;
            }
            set {
                this.fechaCancelacionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaSuspension {
            get {
                return this.fechaSuspensionField;
            }
            set {
                this.fechaSuspensionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSuspensionSpecified {
            get {
                return this.fechaSuspensionFieldSpecified;
            }
            set {
                this.fechaSuspensionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaReinicio {
            get {
                return this.fechaReinicioField;
            }
            set {
                this.fechaReinicioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaReinicioSpecified {
            get {
                return this.fechaReinicioFieldSpecified;
            }
            set {
                this.fechaReinicioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string secundaria {
            get {
                return this.secundariaField;
            }
            set {
                this.secundariaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoIdentificacionSd tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public provinciaSd provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public parroquiaSd parroquia {
            get {
                return this.parroquiaField;
            }
            set {
                this.parroquiaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cantonSd canton {
            get {
                return this.cantonField;
            }
            set {
                this.cantonField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public actividadEconomicaSd actividadEconomica {
            get {
                return this.actividadEconomicaField;
            }
            set {
                this.actividadEconomicaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://producer.ws.equivida.com/")]
    public partial class personaNaturalSd {
        
        private int secPersonaNaturalField;
        
        private bool secPersonaNaturalFieldSpecified;
        
        private tipoIdentificacionSd tipoIdentificacionField;
        
        private string identificacionField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string primerNombreField;
        
        private string segundoNombreField;
        
        private string sexoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private System.DateTime fechaMatrimonioField;
        
        private bool fechaMatrimonioFieldSpecified;
        
        private System.DateTime fechaFallecimientoField;
        
        private bool fechaFallecimientoFieldSpecified;
        
        private informacionAdicionalSd[] informacionAdicionalField;
        
        private empleoDependienteSd[] empleoDependienteField;
        
        private profesionSd profesionField;
        
        private paisSd paisField;
        
        private estadoCivilSd estadoCivilField;
        
        private relacionSd conyugeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int secPersonaNatural {
            get {
                return this.secPersonaNaturalField;
            }
            set {
                this.secPersonaNaturalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secPersonaNaturalSpecified {
            get {
                return this.secPersonaNaturalFieldSpecified;
            }
            set {
                this.secPersonaNaturalFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tipoIdentificacionSd tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string primerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                this.primerNombreField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string segundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaMatrimonio {
            get {
                return this.fechaMatrimonioField;
            }
            set {
                this.fechaMatrimonioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaMatrimonioSpecified {
            get {
                return this.fechaMatrimonioFieldSpecified;
            }
            set {
                this.fechaMatrimonioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime fechaFallecimiento {
            get {
                return this.fechaFallecimientoField;
            }
            set {
                this.fechaFallecimientoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFallecimientoSpecified {
            get {
                return this.fechaFallecimientoFieldSpecified;
            }
            set {
                this.fechaFallecimientoFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("informacionAdicional", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public informacionAdicionalSd[] informacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("empleoDependiente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public empleoDependienteSd[] empleoDependiente {
            get {
                return this.empleoDependienteField;
            }
            set {
                this.empleoDependienteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public profesionSd profesion {
            get {
                return this.profesionField;
            }
            set {
                this.profesionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public paisSd pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public estadoCivilSd estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public relacionSd conyuge {
            get {
                return this.conyugeField;
            }
            set {
                this.conyugeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void processPackageCompletedEventHandler(object sender, processPackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void FindIdentificationNumberCompletedEventHandler(object sender, FindIdentificationNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindIdentificationNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindIdentificationNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public personaSd Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((personaSd)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591